version: "2.4"
services:
  gatesimulator:
    build: 
      context: ./
      dockerfile: dockerfile-gate-simulator
    ports:
      - "9999:9999"
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
  aqashop:
    depends_on:
      - postgres
      - gatesimulator
    build: 
      context: ./
      dockerfile: dockerfile-aqashop
    ports:
      - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"

